### ISSUE TITLE
VcLib 2.0 (MVP)

### ISSUE THREAD

**Issue by philpotisk** [walt-id/waltid-roadmap#44]

**Comment by waltkb** [comment]
Done:

- Implement credential hierachy (AccreditedVerifiableAttestation: VerifiableCredential -> VerifiableAttestation -> AccreditedVerifiableAttestation)
    - Makes EBSI VC conformance, as they also implement a hierachy in their JSON schemas
    - Makes implementation (code) of sub-credentials further down in the hierachy much more compact and thus simpler
    - Avoids reimplementation of inherited attributes
    - New workflow for _correct_ credentials: EBSI JSON Schema -> Credential instead of EBSI example credential JSON -> Credential
    - Now offer correct implementation for VerifiableAttestation atributes (6 dates, etc)
- Polymorphic deserialization for credentials in such a hierachy (so as to match all applied credentials)
    - see above
- Very simple to use serialization of Credential types to JSON, now no longer needing confusing JSON rewrites & attribute renaming or ignoring JSON attributes (thus improving developer experience a lot)
- Present credentials in a dynamic VerifiablePresentation, which can be polymorphically deserialized again

**Comment by philpotisk** [comment]
Open topic:
- VC template generator
   - without hierarchy
   - full support of hierarchy (e.g. for handling EBSI credentials)
- Integration with SSI kit
- Light weight VcLib, without type info? Could be useful for mobile SDK.
